kind: EncryptionConfig
apiVersion: v1
resources:
    - resources:
        - secrets
      providers:
        - aescbc:
            keys:
                - name: key1
                  secret: 3B3IdWDE/ydkN21eNTfqPlDCfe7YJcc8w9GmuD3KXq8=
        - identity: {}
